#!/usr/bin/env bash
# Installation des dépendances

brew install docker docker-compose docker-machine docker-machine-driver-xhyve docker-machine-nfs xhyve
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
