version: "3"
networks:
  dgraph:
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: dgraph zero --my=zero:5080 --replicas 3

  alpha_1:
    image: dgraph/dgraph:latest
    hostname: "alpha_1"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    depends_on:
      - "zero"
    deploy:
      placement:
        constraints:
          - node.role == worker
    command: dgraph alpha --my=alpha_1:7080 --lru_mb=2048 --zero=zero:5080

  alpha_2:
    image: dgraph/dgraph:latest
    hostname: "alpha_2"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    networks:
      - dgraph
    depends_on:
      - "zero"
    deploy:
      placement:
        constraints:
          - node.role == worker
    command: dgraph alpha --my=alpha_2:7081 --lru_mb=2048 --zero=zero:5080 -o 1

  alpha_3:
    image: dgraph/dgraph:latest
    hostname: "alpha_3"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    depends_on:
      - "zero"
    deploy:
      placement:
        constraints:
          - node.role == worker
    command: dgraph alpha --my=alpha_3:7082 --lru_mb=2048 --zero=zero:5080 -o 2


  ratel:
    image: dgraph/dgraph:latest
    hostname: "ratel"
    ports:
      - 8000:8000
    networks:
      - dgraph
    command: dgraph-ratel
    depends_on:
      - "zero"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  data-volume: