version: '3.4'
services:
  web:
    image: dockercloud/hello-world
    ports:
      - target: 80
        published: 81
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      placement:
        preferences:
          - spread: node.labels.zone
        constraints:
          - node.role == worker